### PR TITLE
Remove reference to sourceMappingURL, fix dependencies, bump faye to 1.1.2, and bump to version 2.0.3.

### LINKED ISSUE #86: Please include faye-browser-min.js.map on the assets
I've seen a lot of 404 errors on the browser tries to get the faye-browser-min.js.map file.

Exemple:
ActionController::RoutingError (No route matches [GET] "/assets/faye-browser-min.js.map"):

### PR DESCRIPTION
**Pull request by synthead**
Fixes #86 and #31.

Includes some gemspec changes necessary for a successful build, and includes a bump to 2.0.2 to reflect said changes.

### CODE REVIEW

**Comment by synthead** [comment]
Added commit to bump faye to 1.1.2 (fixes #81).

**Comment by jamesotron** [comment]
Looks like you need to change the `.travis.yml` to build against Ruby 2.[2-3]. Want to give that a go?

**Comment by synthead** [comment]
Sure!  Just added 2.2.5 and 2.3.1 to .travis.yml.

**Comment by synthead** [comment]
It looks like 1.9.3 and 2.0.0 are not supported with some current gem dependencies.  If the versions were locked in the gemspec, you could support 1.9.3 and 2.0.0, but these versions are pretty old now.  I yanked them out (which is what I think you actually meant by "change" ;) ).

Let me know if this works!

**Comment by jamesotron** [comment]
Thanks!

**Comment by synthead** [comment]
You're welcome!  Thanks for the merge!

**Pull request merged**
